services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: custom-mysql:latest
    #image: mysql:9.3
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      #- ./init-scripts:/docker-entrypoint-initdb.d:ro
      #- ./init-scripts/db-hotfix.sql:/tmp/db-hotfix.sql:ro
    command: >
      bash -c "
        docker-entrypoint.sh mysqld &
        echo 'Waiting for SQL...' &&
        until mysqladmin ping -h localhost --silent; do sleep 2; done &&
        echo 'Running hotfix...' &&
        mysql -uroot -p$$MYSQL_ROOT_PASSWORD < /hotfixes/db-hotfix.sql &&
        echo ''Hotfix complete. SQL Started.' &&
        wait
      "
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: arnies-cakes:latest
    #entrypoint: ["./init-scripts/init-gallery.sh"]
    #command: ["node", "src/server.js"]
    env_file:
      - ./src/config/.env.prod
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    restart: always
    ports:
      - "3305:3305"
    volumes:
      - gallery_data:/usr/src/app/src/public/gallery
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volumeUSB1/usbshare/arnies-cakes/db

  gallery_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volumeUSB1/usbshare/arnies-cakes/src/public/gallery

  hotfixes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volumeUSB1/usbshare/arnies-cakes/hotfixes